### PR TITLE
Implement support for IN-19 tubes.

### PR DESCRIPTION
**Pull request by rtrbt**
Hi,
I've implemented support for IN-19(A,B and V) tubes. They are the same size as IN-14 tubes and work perfectly with exixe-14 modules.

Supported symbols are represented as enum values in the arduino library and map directly to IN-14 digits. The show_symbol method can be used for better readability.

The pin mapping is documented in in-19_pin_mapping.md.

### CODE REVIEW

**Comment by dekuNukem** [comment]
Hi rtrbt!

Thank you very much for the contribution. However, I do feel that the extensive code change makes the library a bit bloated, as I prefer a simple and clean codebase. Those IN-19 tube users can simply look up the corresponding number in the very useful `in-19_pin_mapping.md` and use that instead.

I also feel that the other small edits mentioning (rather niche)IN-19 throughout the docs are slightly out of place as well, since most users would be using IN-12 and IN-14 with numbers.

That said, I do believe that the information you're contributing is extremely valuable, and I'd love to include it. If you would, could you please resubmit with other files unchanged, and consolidate all your findings into one file like the current `in-19_pin_mapping.md`? This way can mention the IN-19 in other docs and direct the readers into that file where they can find all the information.

Thanks,

dekuNukem

**Comment by rtrbt** [comment]
Hi,
No problem, I've changed the commit. I was unsure where to add the reference to in-19_pin_mapping.md, so at the moment there is none, do you have any preference other than just linking it in unsupported_tubes.md?

Cheers,
Erik

**Comment by dekuNukem** [comment]
Hi Erik:

You just need to put all the information in `in-19_pin_mapping.md` (or any other name you like), and I'll update the rest of the docs myself to link readers into your file.

Allen

**Comment by rtrbt** [comment]
I've already done that and squashed the commit to not pollute your history.

**Comment by rtrbt** [comment]
Awesome, thank you!

**Pull request merged**
